#!/bin/bash
# Generated by cc-statusline v1.4.0 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2026-02-28T08:26:59.694Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, tokens, burnrate, session
STATUSLINE_VERSION="1.4.0"

input=$(cat)

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- terminal width detection ----
# Claude Code clips each row of statusline output to the terminal width, so we adapt
# line 2 verbosity to avoid the bottom row being hidden on narrow terminals.
# Priority: CS_STATUSLINE_WIDTH override > COLUMNS env > ancestor-pts probe > 100 fallback.
term_cols_src="override"
term_cols="${CS_STATUSLINE_WIDTH:-}"
if ! [[ "$term_cols" =~ ^[0-9]+$ ]] || [ "$term_cols" -le 0 ]; then
  term_cols="${COLUMNS:-}"; term_cols_src="COLUMNS"
fi
if ! [[ "$term_cols" =~ ^[0-9]+$ ]] || [ "$term_cols" -le 0 ]; then
  # Claude Code does not propagate COLUMNS to subprocess, but its own process is
  # still connected to the pts device. Walk up the process tree to find an ancestor
  # with a /dev/pts/* fd, then read the terminal size via stty.
  _pid=$$
  for _i in 1 2 3 4 5; do
    _ppid=$(awk '/PPid:/{print $2}' /proc/$_pid/status 2>/dev/null)
    [[ "$_ppid" =~ ^[0-9]+$ ]] && [ "$_ppid" -gt 0 ] || break
    for _fd in 0 1 2; do
      _dev=$(readlink /proc/$_ppid/fd/$_fd 2>/dev/null)
      if [[ "$_dev" == /dev/pts/* ]]; then
        _c=$(stty size < "$_dev" 2>/dev/null | awk '{print $2}')
        if [[ "$_c" =~ ^[0-9]+$ ]] && [ "$_c" -gt 0 ]; then
          term_cols=$_c; term_cols_src="pts:$_dev"; break 2
        fi
      fi
    done
    _pid=$_ppid
  done
  unset _pid _ppid _i _fd _dev _c
fi
if ! [[ "$term_cols" =~ ^[0-9]+$ ]] || [ "$term_cols" -le 0 ]; then
  term_cols=100; term_cols_src="fallback"
fi

# Layout: binary — full or compact. Previous 4-tier logic left narrow terminals
# in edge cases where line 2 still got clipped. Compact is aggressive (drops
# everything low-priority, splits Weekly to its own row) so it fits everywhere.
# full    : "Session: 24% used, resets in 1h 12m [==--------]"  (all inline, bars)
# compact : "S: 24% 1h12m" — short labels, no bars, Weekly on its own row,
#           line 1 drops 🎨 style, 📟 version, and " (1M context)" suffix
if [ "$term_cols" -ge 140 ]; then
  sl_layout="full"
else
  sl_layout="compact"
fi

# Get the directory where this statusline script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/statusline.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# ---- logging ----
{
  echo "[$TIMESTAMP] Status line triggered (cc-statusline v${STATUSLINE_VERSION})"
  echo "[$TIMESTAMP] Input:"
  if [ "$HAS_JQ" -eq 1 ]; then
    echo "$input" | jq . 2>/dev/null || echo "$input"
    echo "[$TIMESTAMP] Using jq for JSON parsing"
  else
    echo "$input"
    echo "[$TIMESTAMP] WARNING: jq not found, using bash fallback for JSON parsing"
  fi
  echo "---"
} >> "$LOG_FILE" 2>/dev/null

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple  
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
fi

# ---- context window calculation (native) ----
context_pct=""
context_remaining_pct=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;37m'; fi; }  # default white

if [ "$HAS_JQ" -eq 1 ]; then
  # Get context window size and current usage from native Claude Code input
  CONTEXT_SIZE=$(echo "$input" | jq -r '.context_window.context_window_size // 200000' 2>/dev/null)
  USAGE=$(echo "$input" | jq '.context_window.current_usage' 2>/dev/null)

  if [ "$USAGE" != "null" ] && [ -n "$USAGE" ]; then
    # Calculate current context from current_usage fields
    # Formula: input_tokens + cache_creation_input_tokens + cache_read_input_tokens
    CURRENT_TOKENS=$(echo "$USAGE" | jq '(.input_tokens // 0) + (.cache_creation_input_tokens // 0) + (.cache_read_input_tokens // 0)' 2>/dev/null)

    if [ -n "$CURRENT_TOKENS" ] && [ "$CURRENT_TOKENS" -gt 0 ] 2>/dev/null; then
      context_used_pct=$(( CURRENT_TOKENS * 100 / CONTEXT_SIZE ))
      context_remaining_pct=$(( 100 - context_used_pct ))
      # Clamp to valid range
      (( context_remaining_pct < 0 )) && context_remaining_pct=0
      (( context_remaining_pct > 100 )) && context_remaining_pct=100

      # Set color based on remaining percentage
      if [ "$context_remaining_pct" -le 20 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
      elif [ "$context_remaining_pct" -le 40 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
      else
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
      fi

      context_pct="${context_remaining_pct}%"
    fi
  fi
fi

# ---- usage limit (from ratelimit-probe.sh cache) ----
rl_session_txt=""; rl_session_pct=0; rl_session_bar=""
rl_weekly_txt=""; rl_weekly_pct=0; rl_weekly_bar=""
rl_status=""
rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # default mint
rl_weekly_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;153m'; fi; }  # default light blue

RATELIMIT_CACHE="$HOME/.claude/ratelimit-cache.json"
rl_error_msg=""
rl_error_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach/warning
if [ -f "$RATELIMIT_CACHE" ] && [ "$HAS_JQ" -eq 1 ]; then
  rl_json=$(cat "$RATELIMIT_CACHE" 2>/dev/null)
  rl_status=$(echo "$rl_json" | jq -r '.status // "unknown"' 2>/dev/null)

  # Handle probe errors — show diagnostic hint in statusline
  if [ "$rl_status" = "error" ]; then
    rl_error_msg=$(echo "$rl_json" | jq -r '.errorMsg // "unknown error"' 2>/dev/null)
  fi

  rl_reset=$(echo "$rl_json" | jq -r '.resetsAt // empty' 2>/dev/null)

  # Session (5-hour) utilization
  rl_s_util=$(echo "$rl_json" | jq -r '.session.utilization // empty' 2>/dev/null)
  rl_s_reset=$(echo "$rl_json" | jq -r '.session.resetsAt // empty' 2>/dev/null)

  if [ -n "$rl_s_util" ] && [ "$rl_s_util" != "null" ]; then
    rl_session_pct=$(echo "$rl_s_util" | awk '{printf "%d", $1 * 100}')
    rl_session_bar=$(progress_bar "$rl_session_pct" 10)
    if [ -n "$rl_s_reset" ] && [ "$rl_s_reset" != "null" ]; then
      now_sec=$(date +%s)
      rl_s_reset_int=$(printf '%.0f' "$rl_s_reset")
      rl_remaining=$(( rl_s_reset_int - now_sec ))
      (( rl_remaining < 0 )) && rl_remaining=0
      rl_rh=$(( rl_remaining / 3600 )); rl_rm=$(( (rl_remaining % 3600) / 60 ))
      if [ "$sl_layout" = "full" ]; then
        rl_session_txt="${rl_session_pct}% used, resets in ${rl_rh}h ${rl_rm}m"
      else
        rl_session_txt="${rl_session_pct}% ${rl_rh}h${rl_rm}m"
      fi
    else
      if [ "$sl_layout" = "full" ]; then
        rl_session_txt="${rl_session_pct}% used"
      else
        rl_session_txt="${rl_session_pct}%"
      fi
    fi
    # Color based on utilization
    if [ "$rl_session_pct" -ge 90 ]; then
      rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
    elif [ "$rl_session_pct" -ge 70 ]; then
      rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
    fi
  fi

  # Rejected state (hit the limit)
  if [ "$rl_status" = "rejected" ]; then
    rl_session_pct=100
    rl_session_bar=$(progress_bar 100 10)
    if [ -n "$rl_reset" ] && [ "$rl_reset" != "null" ]; then
      now_sec=$(date +%s)
      rl_reset_int=$(printf '%.0f' "$rl_reset")
      rl_remaining=$(( rl_reset_int - now_sec ))
      (( rl_remaining < 0 )) && rl_remaining=0
      rl_rh=$(( rl_remaining / 3600 )); rl_rm=$(( (rl_remaining % 3600) / 60 ))
      if [ "$sl_layout" = "full" ]; then
        rl_session_txt="LIMIT HIT, resets in ${rl_rh}h ${rl_rm}m"
      else
        rl_session_txt="LIMIT ${rl_rh}h${rl_rm}m"
      fi
    else
      rl_session_txt="LIMIT HIT"
    fi
    rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;38;5;203m'; fi; }  # bold red
  fi

  # Weekly (7-day) utilization
  rl_w_util=$(echo "$rl_json" | jq -r '.weekly.utilization // empty' 2>/dev/null)
  rl_w_reset=$(echo "$rl_json" | jq -r '.weekly.resetsAt // empty' 2>/dev/null)

  if [ -n "$rl_w_util" ] && [ "$rl_w_util" != "null" ]; then
    rl_weekly_pct=$(echo "$rl_w_util" | awk '{printf "%d", $1 * 100}')
    rl_weekly_bar=$(progress_bar "$rl_weekly_pct" 10)
    if [ -n "$rl_w_reset" ] && [ "$rl_w_reset" != "null" ]; then
      now_sec=$(date +%s)
      rl_w_reset_int=$(printf '%.0f' "$rl_w_reset")
      rl_w_remaining=$(( rl_w_reset_int - now_sec ))
      (( rl_w_remaining < 0 )) && rl_w_remaining=0
      rl_wd=$(( rl_w_remaining / 86400 )); rl_wh=$(( (rl_w_remaining % 86400) / 3600 ))
      if [ "$sl_layout" = "full" ]; then
        rl_weekly_txt="${rl_weekly_pct}% used, resets in ${rl_wd}d ${rl_wh}h"
      else
        rl_weekly_txt="${rl_weekly_pct}% ${rl_wd}d${rl_wh}h"
      fi
    else
      if [ "$sl_layout" = "full" ]; then
        rl_weekly_txt="${rl_weekly_pct}% used"
      else
        rl_weekly_txt="${rl_weekly_pct}%"
      fi
    fi
    if [ "$rl_weekly_pct" -ge 80 ]; then
      rl_weekly_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
    fi
  fi
fi

# ---- log extracted data ----
{
  echo "[$TIMESTAMP] Extracted: dir=${current_dir:-}, model=${model_name:-}, version=${model_version:-}, git=${git_branch:-}, context=${context_pct:-}, rl_status=${rl_status:-}, rl_session=${rl_session_pct:-}%, rl_weekly=${rl_weekly_pct:-}%"
  echo "[$TIMESTAMP] Width: term_cols=${term_cols} (source=${term_cols_src}) layout=${sl_layout}"
  if [ "$HAS_JQ" -eq 0 ]; then
    echo "[$TIMESTAMP] Note: Context, tokens, and session info require jq for full functionality"
  fi
} >> "$LOG_FILE" 2>/dev/null

# ---- session label from cs tool ----
label_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;38;5;214m'; fi; }  # bold orange
session_label=""
CS_LABELS_FILE="${HOME}/.claude/session-labels.json"
if [ -f "$CS_LABELS_FILE" ] && [ -n "$session_id" ]; then
  if [ "$HAS_JQ" -eq 1 ]; then
    session_label=$(jq -r --arg sid "$session_id" '.[$sid] // empty' "$CS_LABELS_FILE" 2>/dev/null)
  else
    session_label=$(python3 -c "import json,sys; d=json.load(open('$CS_LABELS_FILE')); print(d.get(sys.argv[1],''))" "$session_id" 2>/dev/null)
  fi
fi

# ---- render statusline ----
# Line 1: Core info (directory, git, model, claude code version, output style)
if [ -n "$session_label" ]; then
  printf '🏷️ %s%s%s  ' "$(label_color)" "$session_label" "$(rst)"
fi
printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
if [ -n "$git_branch" ]; then
  printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
fi
# In compact, drop " (1M context)" suffix and the two lowest-priority segments
# (cc_version, output_style) so line 1 never exceeds a narrow terminal.
model_display="$model_name"
[ "$sl_layout" = "compact" ] && model_display="${model_display% (1M context)}"
printf '  🤖 %s%s%s' "$(model_color)" "$model_display" "$(rst)"
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ] && [ "$sl_layout" = "full" ]; then
  printf '  📟 %sv%s%s' "$(cc_version_color)" "$cc_version" "$(rst)"
fi
if [ -n "$output_style" ] && [ "$output_style" != "null" ] && [ "$sl_layout" = "full" ]; then
  printf '  🎨 %s%s%s' "$(style_color)" "$output_style" "$(rst)"
fi

# Lines 2+: Context and usage limits.
# - full:    single row with Ctx + Session + Weekly and progress bars
# - compact: short labels, no bars, Weekly on its own row
if [ "$sl_layout" = "full" ]; then
  sl_show_bars=1
  sl_s_label="Session"
  sl_w_label="Weekly"
else
  sl_show_bars=0
  sl_s_label="S"
  sl_w_label="W"
fi

# Build each segment independently so we can recombine across rows.
ctx_seg=""
if [ -n "$context_pct" ]; then
  if [ "$sl_show_bars" -eq 1 ]; then
    context_bar=$(progress_bar "$context_remaining_pct" 10)
    ctx_seg="🧠 $(context_color)Ctx: ${context_pct} [${context_bar}]$(rst)"
  else
    ctx_seg="🧠 $(context_color)Ctx: ${context_pct}$(rst)"
  fi
else
  ctx_seg="🧠 $(context_color)Ctx: TBD$(rst)"
fi

usage_seg=""
if [ -n "$rl_error_msg" ]; then
  usage_seg="⚠️ $(rl_error_color)Usage: ${rl_error_msg}$(rst)"
elif [ -n "$rl_session_txt" ]; then
  if [ "$sl_show_bars" -eq 1 ]; then
    usage_seg="⚡ $(rl_color)${sl_s_label}: ${rl_session_txt} [${rl_session_bar}]$(rst)"
  else
    usage_seg="⚡ $(rl_color)${sl_s_label}: ${rl_session_txt}$(rst)"
  fi
fi

weekly_seg=""
if [ -n "$rl_weekly_txt" ]; then
  if [ "$sl_show_bars" -eq 1 ]; then
    weekly_seg="📊 $(rl_weekly_color)${sl_w_label}: ${rl_weekly_txt} [${rl_weekly_bar}]$(rst)"
  else
    weekly_seg="📊 $(rl_weekly_color)${sl_w_label}: ${rl_weekly_txt}$(rst)"
  fi
fi

# Compose rows: one row in full/tight/compact; split Weekly to its own row in minimal.
line2="$ctx_seg"
[ -n "$usage_seg" ] && line2="${line2}  ${usage_seg}"

line3=""
if [ "$sl_layout" = "full" ]; then
  [ -n "$weekly_seg" ] && line2="${line2}  ${weekly_seg}"
else
  line3="$weekly_seg"
fi

# Print
printf '\n%s' "$line2"
[ -n "$line3" ] && printf '\n%s' "$line3"
printf '\n'
