#!/bin/bash
# Generated by cc-statusline v1.4.0 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2026-02-28T08:26:59.694Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, tokens, burnrate, session
STATUSLINE_VERSION="1.4.0"

input=$(cat)

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- terminal width detection ----
# Claude Code clips each row of statusline output to the terminal width, so we adapt
# line 2 verbosity to avoid the bottom row being hidden on narrow terminals.
# Priority: CS_STATUSLINE_WIDTH override > COLUMNS env > ancestor-pts probe > 100 fallback.
term_cols_src="override"
term_cols="${CS_STATUSLINE_WIDTH:-}"
if ! [[ "$term_cols" =~ ^[0-9]+$ ]] || [ "$term_cols" -le 0 ]; then
  term_cols="${COLUMNS:-}"; term_cols_src="COLUMNS"
fi
if ! [[ "$term_cols" =~ ^[0-9]+$ ]] || [ "$term_cols" -le 0 ]; then
  # Claude Code does not propagate COLUMNS to subprocess, but its own process is
  # still connected to the pts device. Walk up the process tree to find an ancestor
  # with a /dev/pts/* fd, then read the terminal size via stty.
  _pid=$$
  for _i in 1 2 3 4 5; do
    _ppid=$(awk '/PPid:/{print $2}' /proc/$_pid/status 2>/dev/null)
    [[ "$_ppid" =~ ^[0-9]+$ ]] && [ "$_ppid" -gt 0 ] || break
    for _fd in 0 1 2; do
      _dev=$(readlink /proc/$_ppid/fd/$_fd 2>/dev/null)
      if [[ "$_dev" == /dev/pts/* ]]; then
        _c=$(stty size < "$_dev" 2>/dev/null | awk '{print $2}')
        if [[ "$_c" =~ ^[0-9]+$ ]] && [ "$_c" -gt 0 ]; then
          term_cols=$_c; term_cols_src="pts:$_dev"; break 2
        fi
      fi
    done
    _pid=$_ppid
  done
  unset _pid _ppid _i _fd _dev _c
fi
if ! [[ "$term_cols" =~ ^[0-9]+$ ]] || [ "$term_cols" -le 0 ]; then
  term_cols=100; term_cols_src="fallback"
fi

# Layout: width never costs you a segment. Each segment is built at three verbosity
# tiers and packed into as many rows as the real width needs, so a split pane shows
# the same segments a full-width window does — terser, and wrapped if necessary.
#   tier 1: "Session: 24% used, resets in 1h 12m [==--------]"   (bars, long labels)
#   tier 2: "Session: 24% used, 1h12m"                           (long labels, no bars)
#   tier 3: "S: 24% 1h12m"                                       (short labels)
# CS_STATUSLINE_MAX_ROWS is the row budget per group; the richest tier that fits in it
# wins. If even tier 3 overflows the budget it wraps onto extra rows rather than clip.
sl_max_rows="${CS_STATUSLINE_MAX_ROWS:-1}"
[[ "$sl_max_rows" =~ ^[0-9]+$ ]] && [ "$sl_max_rows" -ge 1 ] || sl_max_rows=1

# Get the directory where this statusline script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="${SCRIPT_DIR}/statusline.log"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# ---- logging ----
# Off unless asked for. This dumps the whole stdin payload on every render, which was
# survivable while renders were event-driven but is not now that statusLine.refreshInterval
# keeps every session rendering on a timer: six idle sessions produce ~720 renders an hour,
# about 20MB of log a day that nobody reads. Turn it on with CS_STATUSLINE_LOG=1 when
# something needs diagnosing; it rotates at CS_STATUSLINE_LOG_MAX bytes (1MB) so even then
# it cannot grow without bound.
sl_log="${CS_STATUSLINE_LOG:-0}"
[ "$sl_log" = "1" ] || LOG_FILE=""

if [ -n "$LOG_FILE" ]; then
  sl_log_max="${CS_STATUSLINE_LOG_MAX:-1048576}"
  [[ "$sl_log_max" =~ ^[0-9]+$ ]] || sl_log_max=1048576
  sl_log_size=$(stat -c %s "$LOG_FILE" 2>/dev/null || stat -f %z "$LOG_FILE" 2>/dev/null || echo 0)
  if [ "$sl_log_size" -gt "$sl_log_max" ] 2>/dev/null; then
    mv -f "$LOG_FILE" "${LOG_FILE}.1" 2>/dev/null
  fi
  {
    echo "[$TIMESTAMP] Status line triggered (cc-statusline v${STATUSLINE_VERSION})"
    echo "[$TIMESTAMP] Input:"
    if [ "$HAS_JQ" -eq 1 ]; then
      echo "$input" | jq . 2>/dev/null || echo "$input"
      echo "[$TIMESTAMP] Using jq for JSON parsing"
    else
      echo "$input"
      echo "[$TIMESTAMP] WARNING: jq not found, using bash fallback for JSON parsing"
    fi
    echo "---"
  } >> "$LOG_FILE" 2>/dev/null
fi

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple  
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
fi

# ---- context window (native remaining_percentage, all users) ----
# Claude Code provides context_window.remaining_percentage directly (may be null
# before the first API response). Prefer it; fall back to a token calc; else "…".
context_pct=""
context_remaining_pct=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;37m'; fi; }  # default white

if [ "$HAS_JQ" -eq 1 ]; then
  cw_remaining=$(echo "$input" | jq -r '.context_window.remaining_percentage // empty' 2>/dev/null)
else
  cw_remaining=$(echo "$input" | grep -o '"remaining_percentage"[[:space:]]*:[[:space:]]*[0-9.]\+' | head -1 | grep -o '[0-9.]\+$')
fi

# Fallback: derive from current_usage tokens when remaining_percentage is absent
if [ -z "$cw_remaining" ] || [ "$cw_remaining" = "null" ]; then
  if [ "$HAS_JQ" -eq 1 ]; then
    CONTEXT_SIZE=$(echo "$input" | jq -r '.context_window.context_window_size // 200000' 2>/dev/null)
    CURRENT_TOKENS=$(echo "$input" | jq -r '(.context_window.current_usage // {}) | ((.input_tokens // 0) + (.cache_creation_input_tokens // 0) + (.cache_read_input_tokens // 0))' 2>/dev/null)
    if [ -n "$CURRENT_TOKENS" ] && [ "$CURRENT_TOKENS" -gt 0 ] 2>/dev/null; then
      cw_remaining=$(( 100 - CURRENT_TOKENS * 100 / CONTEXT_SIZE ))
    fi
  fi
fi

if [ -n "$cw_remaining" ] && [ "$cw_remaining" != "null" ]; then
  context_remaining_pct=$(awk -v v="$cw_remaining" 'BEGIN{ if(v<0)v=0; if(v>100)v=100; printf "%d", v+0.5 }')
  # Set color based on remaining percentage
  if [ "$context_remaining_pct" -le 20 ]; then
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
  elif [ "$context_remaining_pct" -le 40 ]; then
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
  else
    context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # mint green
  fi
  context_pct="${context_remaining_pct}%"
fi

# ---- usage limits (native rate_limits from stdin) ----
# Claude Code provides rate_limits.{five_hour,seven_day} for Claude.ai subscribers
# (Pro/Max) after the first API response. Each window may be independently absent,
# and the whole object is absent for API-key users — in which case the segment is
# simply hidden. No API probe, no OAuth token, no cache file needed.
rl_session_t1=""; rl_session_t2=""; rl_session_t3=""; rl_session_pct=0; rl_session_bar=""
rl_weekly_t1=""; rl_weekly_t2=""; rl_weekly_t3=""; rl_weekly_pct=0; rl_weekly_bar=""
rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # default mint
rl_weekly_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;153m'; fi; }  # default light blue

CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"

if [ "$HAS_JQ" -eq 1 ]; then
  u5h=$(echo "$input" | jq -r '.rate_limits.five_hour.used_percentage // empty' 2>/dev/null)
  r5h=$(echo "$input" | jq -r '.rate_limits.five_hour.resets_at // empty' 2>/dev/null)
  u7d=$(echo "$input" | jq -r '.rate_limits.seven_day.used_percentage // empty' 2>/dev/null)
  r7d=$(echo "$input" | jq -r '.rate_limits.seven_day.resets_at // empty' 2>/dev/null)
else
  # Pure-bash fallback. Each window object has no nested braces, so [^}]* is safe.
  fh=$(echo "$input" | grep -o '"five_hour"[[:space:]]*:[[:space:]]*{[^}]*}')
  u5h=$(echo "$fh" | grep -o '"used_percentage"[[:space:]]*:[[:space:]]*[0-9.]\+' | grep -o '[0-9.]\+$')
  r5h=$(echo "$fh" | grep -o '"resets_at"[[:space:]]*:[[:space:]]*[0-9]\+' | grep -o '[0-9]\+$')
  sd=$(echo "$input" | grep -o '"seven_day"[[:space:]]*:[[:space:]]*{[^}]*}')
  u7d=$(echo "$sd" | grep -o '"used_percentage"[[:space:]]*:[[:space:]]*[0-9.]\+' | grep -o '[0-9.]\+$')
  r7d=$(echo "$sd" | grep -o '"resets_at"[[:space:]]*:[[:space:]]*[0-9]\+' | grep -o '[0-9]\+$')
fi

# Keep the native windows as this session last heard them, before the cache fill below.
# They are a per-session snapshot: Claude Code only updates them after *this* session's
# API responses, so a window you left idle keeps reporting whatever it was told last.
nat_u5h="$u5h"; nat_r5h="$r5h"; nat_u7d="$u7d"; nat_r7d="$r7d"

# Compare a native window against the cached one. Usage only grows inside a window, so a
# higher percentage for the same resets_at is simply the newer reading — which is how one
# session tells whether the shared cache has moved ahead of it (another session has been
# working) or fallen behind it (this session has usage the cache has not seen yet).
# The two sources round differently (headers keep full precision, the usage endpoint
# rounds to whole percent), so a point of difference does not count as movement.
win_state() { # native_pct native_reset cached_pct cached_reset -> ahead|behind|same|unknown
  awk -v np="$1" -v nr="$2" -v cp="$3" -v cr="$4" 'BEGIN{
    if (np == "" || np == "null" || cp == "") { print "unknown"; exit }
    if (nr != "" && nr != "null" && cr != "" && cr+0 != 0) {
      d = nr - cr; if (d < 0) d = -d
      if (d > 60) { print "behind"; exit }   # window rolled over; cache is a window behind
    }
    d = np - cp
    if (d > 1)  { print "behind"; exit }
    if (d < -1) { print "ahead"; exit }
    print "same"
  }'
}

# ---- auth source: who this session bills to ----
# Sessions can run side by side against different accounts and providers, and look the
# same from inside. Claude Code keeps its own OAuth token and subscription variables out
# of the statusline's environment and puts no auth field on stdin, so the source comes
# from the environment it does pass through, first match wins:
#   1. CS_AUTH_LABEL                               -> the label (a named profile)
#   2. CLAUDE_CODE_USE_BEDROCK / _VERTEX / _FOUNDRY -> the provider
#   3. ANTHROPIC_BASE_URL other than api.anthropic.com -> its host
#   4. ANTHROPIC_API_KEY / ANTHROPIC_AUTH_TOKEN    -> "API key"
#   5. otherwise the claude.ai login stored in the config dir -> its email
# A profile that swaps credentials through a variable Claude Code hides (a token from
# `claude setup-token` in CLAUDE_CODE_OAUTH_TOKEN) is only visible through rule 1, so its
# settings file should set CS_AUTH_LABEL; a settings file's env block reaches every
# process that runs the session, background ones included.
# auth_login=1 means the session runs on the stored login — the only case where the
# shared usage cache, fetched with that login, describes this session.
auth_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;211m'; fi; }  # soft pink
auth_t1=""; auth_t3=""; auth_login=0

if [ -n "${CS_AUTH_LABEL:-}" ]; then
  auth_t1="$CS_AUTH_LABEL"
elif [ -n "${CLAUDE_CODE_USE_BEDROCK:-}" ]; then
  auth_t1="Bedrock"
elif [ -n "${CLAUDE_CODE_USE_VERTEX:-}" ]; then
  auth_t1="Vertex"
elif [ -n "${CLAUDE_CODE_USE_FOUNDRY:-}" ]; then
  auth_t1="Foundry"
else
  auth_host="${ANTHROPIC_BASE_URL:-}"; auth_host="${auth_host#*://}"
  auth_host="${auth_host%%/*}"; auth_host="${auth_host%%:*}"
  if [ -n "$auth_host" ] && [ "$auth_host" != "api.anthropic.com" ]; then
    auth_t1="$auth_host"
    # Terse form keeps the last two labels: api.eu.example.com -> example.com
    auth_t3=$(printf '%s' "$auth_host" | awk -F. 'NF>2 && $NF !~ /^[0-9]+$/ {print $(NF-1)"."$NF; next} {print}')
  elif [ -n "${ANTHROPIC_API_KEY:-}" ] || [ -n "${ANTHROPIC_AUTH_TOKEN:-}" ]; then
    auth_t1="API key"
  else
    auth_login=1
    # The global config lives beside the config dir by default, inside it when
    # CLAUDE_CONFIG_DIR is set.
    if [ -n "${CLAUDE_CONFIG_DIR:-}" ]; then auth_cfg="$CLAUDE_CONFIG_DIR/.claude.json"; else auth_cfg="$HOME/.claude.json"; fi
    if [ -f "$auth_cfg" ]; then
      if [ "$HAS_JQ" -eq 1 ]; then
        auth_t1=$(jq -r '.oauthAccount.emailAddress // empty' "$auth_cfg" 2>/dev/null)
      else
        auth_t1=$(python3 -c 'import json,sys; print((json.load(open(sys.argv[1])).get("oauthAccount") or {}).get("emailAddress") or "")' "$auth_cfg" 2>/dev/null)
      fi
      auth_t3="${auth_t1%%@*}"
    fi
  fi
fi
[ -n "$auth_t3" ] || auth_t3="$auth_t1"
if [ "${CS_AUTH_SEGMENT:-1}" = "0" ]; then auth_t1=""; auth_t3=""; fi

# ---- usage-probe cache ----
# Holds the per-model weekly bucket (Fable, Opus, ...), which is not on the statusline
# stdin at all, plus copies of the session and all-model weekly windows. usage-probe.sh
# reads all of it from the endpoint /usage uses; see the refresh decision further down.
MODEL_USAGE_CACHE="$CLAUDE_DIR/model-usage-cache.json"
MODEL_USAGE_MAX_AGE="${CS_USAGE_MAX_AGE:-1800}"             # ignore the cache past this age
MODEL_USAGE_MIN_INTERVAL="${CS_USAGE_MIN_INTERVAL:-180}"    # floor between refreshes
MODEL_USAGE_ERROR_BACKOFF="${CS_USAGE_ERROR_BACKOFF:-900}"  # slower retry after a failure
mu_names=(); mu_pcts=(); mu_resets=()
mu_note=""; mu_status=""; mu_age=-1; mu_need=0; mu_fresh=0
mu_s_pct=""; mu_s_reset=""; mu_w_pct=""; mu_w_reset=""

if [ "${CS_MODEL_USAGE:-1}" != "0" ] && [ "$auth_login" -eq 1 ] && [ -f "$MODEL_USAGE_CACHE" ]; then
  mu_mtime=$(stat -c %Y "$MODEL_USAGE_CACHE" 2>/dev/null || stat -f %m "$MODEL_USAGE_CACHE" 2>/dev/null || echo 0)
  mu_age=$(( $(date +%s) - mu_mtime ))
  [ "$mu_age" -lt "$MODEL_USAGE_MAX_AGE" ] && mu_fresh=1
  # One TSV record per line: "#" the cache's own state, "s"/"w" the session and
  # all-model weekly windows, "m" a per-model bucket.
  if [ "$HAS_JQ" -eq 1 ]; then
    mu_rows=$(jq -r '["#", (.status // ""), (.errorMsg // "")],
                     ["s", (.session.percent // ""), (.session.resetsAt // "")],
                     ["w", (.weeklyAll.percent // ""), (.weeklyAll.resetsAt // "")],
                     ((.models // [])[] | ["m", .name, (.percent // 0), (.resetsAt // 0)])
                     | @tsv' "$MODEL_USAGE_CACHE" 2>/dev/null)
  else
    mu_rows=$(python3 -c '
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(0)
print("#\t%s\t%s" % (d.get("status") or "", d.get("errorMsg") or ""))
for key, tag in (("session", "s"), ("weeklyAll", "w")):
    win = d.get(key) or {}
    print("%s\t%s\t%s" % (tag, win.get("percent", ""), win.get("resetsAt", "")))
for m in d.get("models") or []:
    print("m\t%s\t%s\t%s" % (m.get("name") or "", m.get("percent") or 0, m.get("resetsAt") or 0))
' "$MODEL_USAGE_CACHE" 2>/dev/null)
  fi
  while IFS=$'\t' read -r mu_k mu_a mu_b mu_c; do
    case "$mu_k" in
      '#')
        mu_status="$mu_a"
        [ "$mu_status" = "ok" ] || mu_note="${mu_b:-$mu_status}"
        ;;
      s) [ "$mu_status" = "ok" ] && [ "$mu_fresh" -eq 1 ] && { mu_s_pct="$mu_a"; mu_s_reset="$mu_b"; } ;;
      w) [ "$mu_status" = "ok" ] && [ "$mu_fresh" -eq 1 ] && { mu_w_pct="$mu_a"; mu_w_reset="$mu_b"; } ;;
      m)
        [ -n "$mu_a" ] || continue
        [ "$mu_fresh" -eq 1 ] || continue
        mu_names+=("$mu_a")
        mu_pcts+=("$(awk -v v="$mu_b" 'BEGIN{ if(v<0)v=0; printf "%d", v+0.5 }')")
        mu_resets+=("$mu_c")
        ;;
    esac
  done <<< "$mu_rows"
  [ "$mu_fresh" -eq 1 ] || mu_note="cache stale (${mu_age}s old)"
fi

# Two cases where the shared cache beats what this session was told:
#   unknown — Claude Code omits rate_limits entirely until a window's first API response,
#             so a freshly opened terminal would otherwise show no Session/Weekly at all;
#   ahead   — you have been working in another window, and this one's snapshot is stale.
# Both are marked with ~ and give way to the native values as soon as they catch up.
mu_s_state="unknown"; mu_w_state="unknown"
if [ "$mu_fresh" -eq 1 ]; then
  mu_s_state=$(win_state "$nat_u5h" "$nat_r5h" "$mu_s_pct" "$mu_s_reset")
  mu_w_state=$(win_state "$nat_u7d" "$nat_r7d" "$mu_w_pct" "$mu_w_reset")
fi
rl_s_cached=0; rl_w_cached=0
if [ -n "$mu_s_pct" ] && { [ "$mu_s_state" = "ahead" ] || [ "$mu_s_state" = "unknown" ]; }; then
  u5h="$mu_s_pct"; r5h="$mu_s_reset"; rl_s_cached=1
fi
if [ -n "$mu_w_pct" ] && { [ "$mu_w_state" = "ahead" ] || [ "$mu_w_state" = "unknown" ]; }; then
  u7d="$mu_w_pct"; r7d="$mu_w_reset"; rl_w_cached=1
fi
rl_s_mark=""; [ "$rl_s_cached" -eq 1 ] && rl_s_mark="~"
rl_w_mark=""; [ "$rl_w_cached" -eq 1 ] && rl_w_mark="~"

# Session (5-hour) window
if [ -n "$u5h" ] && [ "$u5h" != "null" ]; then
  rl_session_pct=$(awk -v v="$u5h" 'BEGIN{ if(v<0)v=0; printf "%d", v+0.5 }')
  rl_session_bar=$(progress_bar "$rl_session_pct" 10)
  if [ -n "$r5h" ] && [ "$r5h" != "null" ]; then
    now_sec=$(date +%s); r5h_int=$(printf '%.0f' "$r5h")
    rem=$(( r5h_int - now_sec )); (( rem < 0 )) && rem=0
    rh=$(( rem / 3600 )); rmm=$(( (rem % 3600) / 60 ))
    if [ "$rl_session_pct" -ge 100 ]; then
      rl_session_t1="${rl_s_mark}LIMIT HIT, resets in ${rh}h ${rmm}m"
      rl_session_t2="${rl_s_mark}LIMIT HIT, ${rh}h${rmm}m"
      rl_session_t3="${rl_s_mark}LIMIT ${rh}h${rmm}m"
    else
      rl_session_t1="${rl_s_mark}${rl_session_pct}% used, resets in ${rh}h ${rmm}m"
      rl_session_t2="${rl_s_mark}${rl_session_pct}% used, ${rh}h${rmm}m"
      rl_session_t3="${rl_s_mark}${rl_session_pct}% ${rh}h${rmm}m"
    fi
  else
    if [ "$rl_session_pct" -ge 100 ]; then
      rl_session_t1="${rl_s_mark}LIMIT HIT"; rl_session_t2="$rl_session_t1"
      rl_session_t3="${rl_s_mark}LIMIT"
    else
      rl_session_t1="${rl_s_mark}${rl_session_pct}% used"; rl_session_t2="$rl_session_t1"
      rl_session_t3="${rl_s_mark}${rl_session_pct}%"
    fi
  fi
  if [ "$rl_session_pct" -ge 100 ]; then
    rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;38;5;203m'; fi; }  # bold red
  elif [ "$rl_session_pct" -ge 90 ]; then
    rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
  elif [ "$rl_session_pct" -ge 70 ]; then
    rl_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
  fi
fi

# Weekly (7-day) window
if [ -n "$u7d" ] && [ "$u7d" != "null" ]; then
  rl_weekly_pct=$(awk -v v="$u7d" 'BEGIN{ if(v<0)v=0; printf "%d", v+0.5 }')
  rl_weekly_bar=$(progress_bar "$rl_weekly_pct" 10)
  if [ -n "$r7d" ] && [ "$r7d" != "null" ]; then
    now_sec=$(date +%s); r7d_int=$(printf '%.0f' "$r7d")
    rem=$(( r7d_int - now_sec )); (( rem < 0 )) && rem=0
    wd=$(( rem / 86400 )); wh=$(( (rem % 86400) / 3600 ))
    if [ "$rl_weekly_pct" -ge 100 ]; then
      rl_weekly_t1="${rl_w_mark}LIMIT HIT, resets in ${wd}d ${wh}h"
      rl_weekly_t2="${rl_w_mark}LIMIT HIT, ${wd}d${wh}h"
      rl_weekly_t3="${rl_w_mark}LIMIT ${wd}d${wh}h"
    else
      rl_weekly_t1="${rl_w_mark}${rl_weekly_pct}% used, resets in ${wd}d ${wh}h"
      rl_weekly_t2="${rl_w_mark}${rl_weekly_pct}% used, ${wd}d${wh}h"
      rl_weekly_t3="${rl_w_mark}${rl_weekly_pct}% ${wd}d${wh}h"
    fi
  else
    if [ "$rl_weekly_pct" -ge 100 ]; then
      rl_weekly_t1="${rl_w_mark}LIMIT HIT"; rl_weekly_t2="$rl_weekly_t1"
      rl_weekly_t3="${rl_w_mark}LIMIT"
    else
      rl_weekly_t1="${rl_w_mark}${rl_weekly_pct}% used"; rl_weekly_t2="$rl_weekly_t1"
      rl_weekly_t3="${rl_w_mark}${rl_weekly_pct}%"
    fi
  fi
  if [ "$rl_weekly_pct" -ge 100 ]; then
    rl_weekly_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;38;5;203m'; fi; }  # bold red
  elif [ "$rl_weekly_pct" -ge 90 ]; then
    rl_weekly_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
  elif [ "$rl_weekly_pct" -ge 80 ]; then
    rl_weekly_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
  fi
fi

# ---- refresh the usage cache, event-driven ----
# A request is only worth making when this session knows something the cache does not:
# its native windows have moved past the cached ones, so the per-model bucket has moved
# too. A session left idle compares equal and asks for nothing, however often it renders
# — the work of refreshing falls on whichever session is actually consuming usage. The
# staleness rule is the backstop for when every session is idle.
# Only a session on the stored login may ask: the probe reads that login's token, and
# its numbers describe that account, not whatever this session bills to.
if [ "${CS_MODEL_USAGE:-1}" != "0" ] && [ "$auth_login" -eq 1 ]; then
  mu_behind=0
  { [ "$mu_s_state" = "behind" ] || [ "$mu_w_state" = "behind" ]; } && mu_behind=1
  # Native windows with nothing cached to compare them to: the cache needs those numbers.
  if [ "$mu_fresh" -eq 1 ] && [ -z "$mu_s_pct" ] && [ -n "$nat_u5h" ] && [ "$nat_u5h" != "null" ]; then
    mu_behind=1
  fi

  if [ ! -f "$MODEL_USAGE_CACHE" ]; then
    mu_need=1
  elif [ "$mu_status" != "ok" ]; then
    [ "$mu_age" -ge "$MODEL_USAGE_ERROR_BACKOFF" ] && mu_need=1
  elif [ "$mu_age" -ge "$MODEL_USAGE_MAX_AGE" ]; then
    mu_need=1
  elif [ "$mu_behind" -eq 1 ]; then
    [ "$mu_age" -ge "$MODEL_USAGE_MIN_INTERVAL" ] && mu_need=1
  fi

  if [ "$mu_need" -eq 1 ]; then
    # Find usage-probe.sh next to the *real* script: `cs install` symlinks this file
    # into $CLAUDE_DIR, where SCRIPT_DIR alone would miss the probe.
    sl_self="${BASH_SOURCE[0]}"
    for _hop in 1 2 3 4 5; do
      [ -L "$sl_self" ] || break
      _link=$(readlink "$sl_self")
      case "$_link" in
        /*) sl_self="$_link" ;;
        *)  sl_self="$(dirname "$sl_self")/$_link" ;;
      esac
    done
    probe="$(cd "$(dirname "$sl_self")" 2>/dev/null && pwd)/usage-probe.sh"
    [ -x "$probe" ] || probe="$SCRIPT_DIR/usage-probe.sh"
    # Detach every fd: a background child still holding our stdout would keep Claude
    # Code waiting on the pipe before it can draw the statusline.
    [ -x "$probe" ] && ( "$probe" </dev/null >/dev/null 2>&1 & )
  fi
fi

# ---- log extracted data ----
if [ -n "$LOG_FILE" ]; then
{
  echo "[$TIMESTAMP] Extracted: dir=${current_dir:-}, model=${model_name:-}, git=${git_branch:-}, ctx=${context_pct:-}, session=${rl_session_pct:-}%, weekly=${rl_weekly_pct:-}%"
  echo "[$TIMESTAMP] Usage cache: ${#mu_names[@]} model bucket(s)${mu_names[0]:+ (${mu_names[0]} ${mu_pcts[0]}%)} status=${mu_status:-none} age=${mu_age}s vs-native=s:${mu_s_state}/w:${mu_w_state} filled=s${rl_s_cached}/w${rl_w_cached} refresh=${mu_need}${mu_note:+ note=${mu_note}}"
  echo "[$TIMESTAMP] Width: term_cols=${term_cols} (source=${term_cols_src}) max_rows=${sl_max_rows}"
} >> "$LOG_FILE" 2>/dev/null
fi

# ---- session label from cs tool ----
label_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;38;5;214m'; fi; }  # bold orange
session_label=""
CS_LABELS_FILE="$CLAUDE_DIR/session-labels.json"
if [ -f "$CS_LABELS_FILE" ] && [ -n "$session_id" ]; then
  if [ "$HAS_JQ" -eq 1 ]; then
    session_label=$(jq -r --arg sid "$session_id" '.[$sid] // empty' "$CS_LABELS_FILE" 2>/dev/null)
  else
    session_label=$(python3 -c "import json,sys; d=json.load(open('$CS_LABELS_FILE')); print(d.get(sys.argv[1],''))" "$session_id" 2>/dev/null)
  fi
fi

# ---- render statusline ----
# Build every segment once at three verbosity tiers, then pack them into rows that fit
# the real terminal width. Two groups: 1 = identity (label, dir, branch, model, version,
# style), 2 = usage (context, session, weekly, per-model weekly). Width no longer costs
# a segment — a narrow pane gets a terser tier, and extra rows if it still doesn't fit.
SEP="  "
RESET_SEQ=$(rst)   # resolved once; add_seg runs for every segment at every tier
seg_group=(); seg_c1=(); seg_c2=(); seg_c3=(); seg_p1=(); seg_p2=(); seg_p3=()

add_seg() { # group icon color-fn text_tier1 text_tier2 text_tier3
  local g="$1" icon="$2" cfn="$3" t1="$4" t2="$5" t3="$6" col
  col=$($cfn)
  seg_group+=("$g")
  seg_p1+=("$icon $t1"); seg_c1+=("$icon ${col}${t1}${RESET_SEQ}")
  seg_p2+=("$icon $t2"); seg_c2+=("$icon ${col}${t2}${RESET_SEQ}")
  seg_p3+=("$icon $t3"); seg_c3+=("$icon ${col}${t3}${RESET_SEQ}")
}

# --- group 1: identity ---
[ -n "$session_label" ] && add_seg 1 "🏷️" label_color "$session_label" "$session_label" "$session_label"
add_seg 1 "📁" dir_color "$current_dir" "$current_dir" "$current_dir"
[ -n "$git_branch" ] && add_seg 1 "🌿" git_color "$git_branch" "$git_branch" "$git_branch"
# The " (1M context)" suffix is worth abbreviating, not dropping.
model_terse="${model_name/ (1M context)/ (1M)}"
add_seg 1 "🤖" model_color "$model_name" "$model_name" "$model_terse"
[ -n "$auth_t1" ] && add_seg 1 "🔑" auth_color "$auth_t1" "$auth_t1" "$auth_t3"
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  add_seg 1 "🏷️" version_color "$model_version" "$model_version" "$model_version"
fi
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ]; then
  add_seg 1 "📟" cc_version_color "v$cc_version" "v$cc_version" "v$cc_version"
fi
if [ -n "$output_style" ] && [ "$output_style" != "null" ]; then
  add_seg 1 "🎨" style_color "$output_style" "$output_style" "$output_style"
fi

# --- group 2: context and usage limits ---
if [ -n "$context_pct" ]; then
  add_seg 2 "🧠" context_color \
    "Ctx: ${context_pct} [$(progress_bar "$context_remaining_pct" 10)]" \
    "Ctx: ${context_pct}" "Ctx: ${context_pct}"
else
  add_seg 2 "🧠" context_color "Ctx: …" "Ctx: …" "Ctx: …"
fi

if [ -n "$rl_session_t1" ]; then
  add_seg 2 "⚡" rl_color "Session: ${rl_session_t1} [${rl_session_bar}]" \
    "Session: ${rl_session_t2}" "S: ${rl_session_t3}"
fi

if [ -n "$rl_weekly_t1" ]; then
  # Once a per-model bucket sits next to it, the 7d total has to say it is the total —
  # "Weekly" alone reads as if it were the only weekly number.
  sl_w_label="Weekly"; sl_w_short="W"
  if [ "${#mu_names[@]}" -gt 0 ]; then sl_w_label="Weekly(all)"; sl_w_short="W(all)"; fi
  add_seg 2 "📊" rl_weekly_color "${sl_w_label}: ${rl_weekly_t1} [${rl_weekly_bar}]" \
    "${sl_w_label}: ${rl_weekly_t2}" "${sl_w_short}: ${rl_weekly_t3}"
fi

# Per-model weekly buckets, usually just one (Fable).
mu_i=0
while [ "$mu_i" -lt "${#mu_names[@]}" ]; do
  mu_name="${mu_names[$mu_i]}"; mu_pct="${mu_pcts[$mu_i]}"; mu_reset="${mu_resets[$mu_i]}"
  mu_i=$(( mu_i + 1 ))

  mu_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;183m'; fi; }  # light violet
  if [ "$mu_pct" -ge 100 ]; then
    mu_color() { if [ "$use_color" -eq 1 ]; then printf '\033[1;38;5;203m'; fi; }  # bold red
  elif [ "$mu_pct" -ge 90 ]; then
    mu_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
  elif [ "$mu_pct" -ge 80 ]; then
    mu_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
  fi

  if [ "$mu_pct" -ge 100 ]; then
    mu_t1="LIMIT HIT"; mu_t2="LIMIT HIT"; mu_t3="LIMIT"
  else
    mu_t1="${mu_pct}% used"; mu_t2="${mu_pct}% used"; mu_t3="${mu_pct}%"
  fi

  # The reset time is only worth the width when it differs from the 7d total's —
  # per-model buckets normally roll over with it.
  if [[ "$mu_reset" =~ ^[0-9]+$ ]] && [ "$mu_reset" -gt 0 ]; then
    mu_r7d=0
    [[ "$r7d" =~ ^[0-9]+$ ]] && mu_r7d="$r7d"
    mu_delta=$(( mu_reset - mu_r7d )); [ "$mu_delta" -lt 0 ] && mu_delta=$(( -mu_delta ))
    if [ "$mu_delta" -gt 300 ]; then
      mu_rem=$(( mu_reset - $(date +%s) )); [ "$mu_rem" -lt 0 ] && mu_rem=0
      mu_d=$(( mu_rem / 86400 )); mu_h=$(( (mu_rem % 86400) / 3600 ))
      mu_t1="${mu_t1}, resets in ${mu_d}d ${mu_h}h"
      mu_t2="${mu_t2}, ${mu_d}d${mu_h}h"
      mu_t3="${mu_t3} ${mu_d}d${mu_h}h"
    fi
  fi

  add_seg 2 "🎭" mu_color "${mu_name}: ${mu_t1} [$(progress_bar "$mu_pct" 10)]" \
    "${mu_name}: ${mu_t2}" "${mu_name}: ${mu_t3}"
done

# --- display width of each tier ---
# python3 measures it properly (CJK session labels and emoji are double-width). Without
# python3 we count bytes, which over-estimates multibyte text and so wraps early rather
# than clipping — the safe direction to be wrong in.
seg_w1=(); seg_w2=(); seg_w3=()
if [ "${#seg_group[@]}" -gt 0 ]; then
  seg_widths=""
  if command -v python3 >/dev/null 2>&1; then
    seg_widths=$(printf '%s\n' "${seg_p1[@]}" "${seg_p2[@]}" "${seg_p3[@]}" | python3 -c '
import sys, unicodedata
def width(s):
    n = 0
    for ch in s:
        if unicodedata.combining(ch) or unicodedata.category(ch) in ("Mn", "Me", "Cf"):
            continue
        o = ord(ch)
        if (unicodedata.east_asian_width(ch) in ("W", "F")
                or 0x1F300 <= o <= 0x1FAFF or 0x2600 <= o <= 0x27BF):
            n += 2
        else:
            n += 1
    return n
for line in sys.stdin.read().splitlines():
    print(width(line))
' 2>/dev/null)
  fi
  seg_n=${#seg_group[@]}
  if [ -n "$seg_widths" ]; then
    seg_i=0
    while IFS= read -r seg_wv; do
      if [ "$seg_i" -lt "$seg_n" ]; then seg_w1+=("$seg_wv")
      elif [ "$seg_i" -lt $(( 2 * seg_n )) ]; then seg_w2+=("$seg_wv")
      else seg_w3+=("$seg_wv"); fi
      seg_i=$(( seg_i + 1 ))
    done <<< "$seg_widths"
  fi
  if [ "${#seg_w3[@]}" -ne "$seg_n" ]; then
    seg_w1=(); seg_w2=(); seg_w3=()
    for (( seg_i=0; seg_i<seg_n; seg_i++ )); do
      seg_w1+=("$(printf '%s' "${seg_p1[$seg_i]}" | wc -c | tr -d ' ')")
      seg_w2+=("$(printf '%s' "${seg_p2[$seg_i]}" | wc -c | tr -d ' ')")
      seg_w3+=("$(printf '%s' "${seg_p3[$seg_i]}" | wc -c | tr -d ' ')")
    done
  fi
fi

# --- pack a group into rows of at most term_cols columns ---
pack_rows=()
pack_group() { # group tier
  pack_rows=()
  local cur="" curw=0 i seg w
  for (( i=0; i<${#seg_group[@]}; i++ )); do
    [ "${seg_group[$i]}" = "$1" ] || continue
    case "$2" in
      1) seg="${seg_c1[$i]}"; w="${seg_w1[$i]}" ;;
      2) seg="${seg_c2[$i]}"; w="${seg_w2[$i]}" ;;
      *) seg="${seg_c3[$i]}"; w="${seg_w3[$i]}" ;;
    esac
    [[ "$w" =~ ^[0-9]+$ ]] || w=${#seg}
    if [ -z "$cur" ]; then
      cur="$seg"; curw="$w"
    elif [ $(( curw + 2 + w )) -le "$term_cols" ]; then
      cur="${cur}${SEP}${seg}"; curw=$(( curw + 2 + w ))
    else
      pack_rows+=("$cur"); cur="$seg"; curw="$w"
    fi
  done
  [ -n "$cur" ] && pack_rows+=("$cur")
}

render_group() { # group — print the richest tier that stays within the row budget
  local tier
  for tier in 1 2 3; do
    pack_group "$1" "$tier"
    [ "${#pack_rows[@]}" -le "$sl_max_rows" ] && break
  done
  [ "${#pack_rows[@]}" -gt 0 ] && printf '%s\n' "${pack_rows[@]}"
}

render_group 1
render_group 2
